# Generated by Django 5.1.2 on 2025-02-06 01:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('activo', models.SmallIntegerField(default=1)),
                ('titulo', models.CharField(max_length=128)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='carrusel/')),
                ('fechacreacion', models.DateField()),
                ('fechapublicacion', models.DateField()),
                ('estado', models.IntegerField()),
                ('idcarrusel', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Carrusel',
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('activo', models.SmallIntegerField(default=1)),
                ('idconf', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombreweb', models.CharField(max_length=128)),
                ('correo', models.CharField(max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=128, null=True)),
                ('estadostreaming', models.IntegerField(blank=True, null=True)),
                ('urlinput', models.TextField(blank=True, null=True)),
                ('urloutput', models.TextField(blank=True, null=True)),
                ('nombrecanal', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Configuracion',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('activo', models.SmallIntegerField(default=1)),
                ('idevento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=128)),
                ('descripcion', models.TextField()),
                ('fechaevento', models.DateField()),
                ('fechacreacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Gallos',
            fields=[
                ('activo', models.SmallIntegerField(default=1)),
                ('nombre', models.BigIntegerField()),
                ('duenio', models.BigIntegerField()),
                ('peso', models.BigIntegerField(blank=True, null=True)),
                ('color', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.BigIntegerField()),
                ('experiencia', models.BigIntegerField(blank=True, null=True)),
                ('fechacreacion', models.BigIntegerField()),
                ('idgallo', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Gallos',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombres', models.CharField(max_length=128)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('apellidos', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fotoperfil', models.ImageField(blank=True, null=True, upload_to='perfilUsuarioimagen/')),
                ('activo', models.BooleanField(default=1)),
                ('instituto', models.CharField(blank=True, max_length=128, null=True)),
                ('pais', models.CharField(blank=True, max_length=128, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tabla', models.CharField(help_text='Nombre de la tabla a la que pertenece este estado', max_length=255)),
                ('identificador_tabla', models.CharField(help_text='Identificador único del registro dentro de la tabla', max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('clave', models.CharField(help_text='Clave del estado', max_length=255)),
                ('valor', models.CharField(help_text='Valor del estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['nombre_tabla', 'identificador_tabla'], name='streaming_e_nombre__85b241_idx')],
                'unique_together': {('nombre_tabla', 'identificador_tabla', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('activo', models.SmallIntegerField(default=1)),
                ('urlstreaming', models.TextField()),
                ('nombrevideolife', models.TextField()),
                ('idstreaming', models.BigIntegerField(primary_key=True, serialize=False)),
                ('idevento', models.ForeignKey(blank=True, db_column='idevento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.evento')),
            ],
            options={
                'db_table': 'Streaming',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('activo', models.SmallIntegerField(default=1)),
                ('comentario', models.TextField()),
                ('idcomentario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateField()),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idstreaming', models.ForeignKey(db_column='idstreaming', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.streaming')),
            ],
            options={
                'db_table': 'Comentario',
            },
        ),
        migrations.CreateModel(
            name='RegistroEvento',
            fields=[
                ('activo', models.SmallIntegerField(default=1)),
                ('voucher', models.BinaryField()),
                ('estado', models.IntegerField()),
                ('idevento', models.OneToOneField(db_column='idevento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='streaming.evento')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_evento',
                'unique_together': {('idevento', 'idusuario')},
            },
        ),
        migrations.CreateModel(
            name='ParticipacionGalllos',
            fields=[
                ('activo', models.SmallIntegerField(default=1)),
                ('idgallo', models.OneToOneField(db_column='idgallo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='streaming.gallos')),
                ('idevento', models.ForeignKey(db_column='idevento', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.evento')),
            ],
            options={
                'db_table': 'participacion_galllos',
                'unique_together': {('idgallo', 'idevento')},
            },
        ),
    ]
