# Generated by Django 5.1.2 on 2025-01-24 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('imagen', models.BinaryField()),
                ('fechacreacion', models.DateField()),
                ('fechapublicacion', models.DateField()),
                ('activo', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('idcarrusel', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Carrusel',
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('idconf', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombreweb', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estadostreaming', models.IntegerField(blank=True, null=True)),
                ('urlinput', models.TextField()),
                ('urloutput', models.TextField()),
                ('nombrecanal', models.CharField(max_length=20)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'Configuracion',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idevento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('fechaevento', models.DateField()),
                ('fechacreacion', models.DateField()),
                ('estado', models.IntegerField()),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Gallos',
            fields=[
                ('nombre', models.BigIntegerField()),
                ('duenio', models.BigIntegerField()),
                ('peso', models.BigIntegerField(blank=True, null=True)),
                ('color', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.BigIntegerField()),
                ('experiencia', models.BigIntegerField(blank=True, null=True)),
                ('activo', models.BigIntegerField()),
                ('fechacreacion', models.BigIntegerField()),
                ('idgallo', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Gallos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('urlstreaming', models.TextField()),
                ('nombrevideolife', models.TextField()),
                ('idstreaming', models.BigIntegerField(primary_key=True, serialize=False)),
                ('idevento', models.ForeignKey(blank=True, db_column='idevento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.evento')),
            ],
            options={
                'db_table': 'Streaming',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('comentario', models.TextField()),
                ('idcomentario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('activo', models.IntegerField()),
                ('fechacreacion', models.DateField()),
                ('idstreaming', models.ForeignKey(db_column='idstreaming', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.streaming')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.usuario')),
            ],
            options={
                'db_table': 'Comentario',
            },
        ),
        migrations.CreateModel(
            name='RegistroEvento',
            fields=[
                ('voucher', models.BinaryField()),
                ('estado', models.IntegerField()),
                ('idevento', models.OneToOneField(db_column='idevento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='streaming.evento')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.usuario')),
            ],
            options={
                'db_table': 'registro_evento',
                'unique_together': {('idevento', 'idusuario')},
            },
        ),
        migrations.CreateModel(
            name='ParticipacionGalllos',
            fields=[
                ('idgallo', models.OneToOneField(db_column='idgallo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='streaming.gallos')),
                ('idevento', models.ForeignKey(db_column='idevento', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.evento')),
            ],
            options={
                'db_table': 'participacion_galllos',
                'unique_together': {('idgallo', 'idevento')},
            },
        ),
    ]
