# Generated by Django 5.1.2 on 2025-02-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='instituto',
        ),
    ]
