# Generated by Django 5.1.2 on 2025-01-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participaciongalllos',
            name='activo',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='activo',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='streaming',
            name='activo',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='activo',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='activo',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='activo',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='evento',
            name='activo',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gallos',
            name='activo',
            field=models.SmallIntegerField(default=1),
        ),
    ]
