# Generated by Django 5.1.2 on 2025-03-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_remove_customuser_instituto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duenio',
            fields=[
                ('idduenio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('eliminado', models.SmallIntegerField(default=0)),
                ('nombres', models.CharField(max_length=128)),
                ('apellidos', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fotoperfil', models.ImageField(blank=True, null=True, upload_to='perfilDuenioimagen/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fechapublicacion', models.DateField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'Duenio',
            },
        ),
        migrations.RemoveField(
            model_name='carrusel',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='carrusel',
            name='fechacreacion',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fechacreacion',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fechacreacion',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fechacreacion',
        ),
        migrations.RemoveField(
            model_name='gallos',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='gallos',
            name='fechacreacion',
        ),
        migrations.RemoveField(
            model_name='participaciongalllos',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='registroevento',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='streaming',
            name='activo',
        ),
        migrations.AddField(
            model_name='carrusel',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comentario',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gallos',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participaciongalllos',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streaming',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
    ]
