# Generated by Django 5.1.2 on 2025-01-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_participaciongalllos_activo_registroevento_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='carrusel/'),
        ),
        migrations.AlterField(
            model_name='carrusel',
            name='titulo',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='correo',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombrecanal',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombreweb',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='telefono',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='urlinput',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='urloutput',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
