# Generated by Django 5.1.2 on 2025-03-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_carrusel_fechacreacion_comentario_fechacreacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallos',
            name='duenio',
        ),
        migrations.AlterField(
            model_name='gallos',
            name='color',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='gallos',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gallos',
            name='experiencia',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gallos',
            name='nombre',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='gallos',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
