# Generated by Django 5.1.2 on 2025-03-15 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_remove_gallos_duenio_alter_gallos_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallos',
            name='idduenio',
            field=models.ForeignKey(db_column='idduenio', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.duenio'),
            preserve_default=False,
        ),
    ]
