# Generated by Django 5.1.2 on 2025-03-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_gallos_idduenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='idcarrusel',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='idcomentario',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='idconf',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='duenio',
            name='idduenio',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='idevento',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gallos',
            name='idgallo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='streaming',
            name='idstreaming',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
