# Generated by Django 5.1.2 on 2025-03-15 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_alter_carrusel_idcarrusel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duenio',
            name='fechapublicacion',
        ),
    ]
