# Generated by Django 5.1.2 on 2025-03-19 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_remove_duenio_fechapublicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiesta',
            fields=[
                ('eliminado', models.SmallIntegerField(default=0)),
                ('idfiesta', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=128)),
                ('descripcion', models.TextField()),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'Fiesta',
            },
        ),
        migrations.AlterUniqueTogether(
            name='registroevento',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='registroevento',
            name='idevento',
        ),
        migrations.RemoveField(
            model_name='registroevento',
            name='idusuario',
        ),
        migrations.RemoveField(
            model_name='gallos',
            name='idduenio',
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventoflayer/'),
        ),
        migrations.AddField(
            model_name='gallos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='gallofoto/'),
        ),
        migrations.AlterField(
            model_name='gallos',
            name='experiencia',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='idfiesta',
            field=models.ForeignKey(db_column='idfiesta', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.fiesta'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Galpon',
            fields=[
                ('idgalpon', models.BigAutoField(primary_key=True, serialize=False)),
                ('eliminado', models.SmallIntegerField(default=0)),
                ('titulo', models.CharField(max_length=128)),
                ('descripcion', models.TextField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField()),
                ('idduenio', models.ForeignKey(db_column='idduenio', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.duenio')),
            ],
            options={
                'db_table': 'Galpon',
            },
        ),
        migrations.CreateModel(
            name='GalponFiesta',
            fields=[
                ('idparticipacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('eliminado', models.SmallIntegerField(default=0)),
                ('idfiesta', models.ForeignKey(db_column='idfiesta', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.fiesta')),
                ('idgalpon', models.ForeignKey(db_column='idgalpon', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.galpon')),
            ],
            options={
                'db_table': 'galpon_fiesta',
            },
        ),
        migrations.CreateModel(
            name='GalponGallos',
            fields=[
                ('idparticipacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('eliminado', models.SmallIntegerField(default=0)),
                ('idgallo', models.ForeignKey(db_column='idgallo', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.gallos')),
                ('idgalpon', models.ForeignKey(db_column='idgalpon', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.galpon')),
            ],
            options={
                'db_table': 'galpon_gallos',
            },
        ),
        migrations.CreateModel(
            name='ParticipacionGallos',
            fields=[
                ('idparticipacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('eliminado', models.SmallIntegerField(default=0)),
                ('idevento', models.ForeignKey(db_column='idevento', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.evento')),
                ('idgallo', models.ForeignKey(db_column='idgallo', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.gallos')),
            ],
            options={
                'db_table': 'participacion_gallos',
            },
        ),
        migrations.CreateModel(
            name='RegistroFiesta',
            fields=[
                ('idregistro', models.BigAutoField(primary_key=True, serialize=False)),
                ('eliminado', models.SmallIntegerField(default=0)),
                ('voucher', models.ImageField(blank=True, null=True, upload_to='pagos/')),
                ('estado', models.IntegerField()),
                ('idfiesta', models.ForeignKey(db_column='idfiesta', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.fiesta')),
                ('idusuario', models.ForeignKey(db_column='idusuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_fiesta',
                'unique_together': {('idfiesta', 'idusuario')},
            },
        ),
        migrations.DeleteModel(
            name='ParticipacionGalllos',
        ),
        migrations.DeleteModel(
            name='RegistroEvento',
        ),
    ]
