# Generated by Django 5.1.2 on 2025-03-19 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0009_fiesta_alter_registroevento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galpongallos',
            name='idgalpon',
            field=models.ForeignKey(db_column='idgalpon', on_delete=django.db.models.deletion.DO_NOTHING, related_name='galpon_gallos', to='streaming.galpon'),
        ),
    ]
