# Generated by Django 5.1.2 on 2025-03-19 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_alter_galpongallos_idgalpon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galpongallos',
            name='idgallo',
            field=models.ForeignKey(db_column='idgallo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='galpon_gallos', to='streaming.gallos'),
        ),
        migrations.AlterField(
            model_name='galpongallos',
            name='idgalpon',
            field=models.ForeignKey(db_column='idgalpon', on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.galpon'),
        ),
    ]
