# Generated by Django 5.1.2 on 2025-03-19 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0012_alter_galpongallos_idgallo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='idfiesta',
            field=models.ForeignKey(db_column='idfiesta', on_delete=django.db.models.deletion.DO_NOTHING, related_name='eventos', to='streaming.fiesta'),
        ),
        migrations.AlterField(
            model_name='galpongallos',
            name='idgallo',
            field=models.ForeignKey(db_column='idgallo', on_delete=django.db.models.deletion.DO_NOTHING, related_name='gallo_galpondetalle', to='streaming.gallos'),
        ),
        migrations.AlterField(
            model_name='participaciongallos',
            name='idevento',
            field=models.ForeignKey(db_column='idevento', on_delete=django.db.models.deletion.DO_NOTHING, related_name='evento_gallos_vs', to='streaming.evento'),
        ),
    ]
