# Generated by Django 5.1.2 on 2025-03-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0013_alter_evento_idfiesta_alter_galpongallos_idgallo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='estado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
