# Generated by Django 5.1.2 on 2025-03-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0014_customuser_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallos',
            name='anillo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='gallos',
            name='placa',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
