# Generated by Django 5.1.2 on 2025-03-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0015_gallos_anillo_gallos_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofiesta',
            name='precio',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
