# Generated by Django 5.1.2 on 2025-03-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0016_registrofiesta_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrofiesta',
            name='precio',
        ),
        migrations.AddField(
            model_name='fiesta',
            name='precio',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
