# Generated by Django 5.1.2 on 2025-04-01 00:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0017_remove_registrofiesta_precio_fiesta_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofiesta',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
