# Generated by Django 5.1.2 on 2025-04-05 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0018_registrofiesta_fechacreacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galpongallos',
            old_name='idparticipacion',
            new_name='idgalpongallos',
        ),
    ]
