# Generated by Django 5.1.2 on 2025-04-05 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0019_rename_idparticipacion_galpongallos_idgalpongallos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galponfiesta',
            old_name='idparticipacion',
            new_name='idgalponfiesta',
        ),
    ]
