# Generated by Django 5.1.2 on 2025-04-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0020_rename_idparticipacion_galponfiesta_idgalponfiesta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion',
            old_name='urlinput',
            new_name='urlinput1',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='urlinput2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
