# Generated by Django 5.1.2 on 2025-04-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0021_rename_urlinput_configuracion_urlinput1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='channel_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
