# Generated by Django 5.1.2 on 2025-04-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0022_configuracion_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='nombrecanal',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
