# Generated by Django 5.1.2 on 2025-04-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0023_alter_configuracion_nombrecanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaming',
            name='urlstreaming',
            field=models.TextField(blank=True, null=True),
        ),
    ]
