# Generated by Django 5.1.2 on 2025-04-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0024_alter_streaming_urlstreaming'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streaming',
            old_name='urlstreaming',
            new_name='urlgrabacion',
        ),
    ]
