# Generated by Django 5.1.2 on 2025-04-08 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0025_rename_urlstreaming_streaming_urlgrabacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participaciongallos',
            name='idgallo',
        ),
        migrations.AddField(
            model_name='participaciongallos',
            name='idgallo1',
            field=models.ForeignKey(db_column='idgallo1', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='combates_como_gallo1', to='streaming.gallos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participaciongallos',
            name='idgallo2',
            field=models.ForeignKey(db_column='idgallo2', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='combates_como_gallo2', to='streaming.gallos'),
            preserve_default=False,
        ),
    ]
