# Generated by Django 5.1.2 on 2025-04-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0026_remove_participaciongallos_idgallo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiesta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Fiestaimagen/'),
        ),
        migrations.AddField(
            model_name='participaciongallos',
            name='culminacion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='participaciongallos',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participaciongallos',
            name='resultado',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
