# Generated by Django 5.1.2 on 2025-04-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0027_fiesta_imagen_participaciongallos_culminacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='estado',
            new_name='isstreaming',
        ),
    ]
