# Generated by Django 5.1.2 on 2025-04-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0028_rename_estado_evento_isstreaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
