# Generated by Django 5.1.2 on 2025-04-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0029_evento_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participaciongallos',
            name='culminacion',
        ),
        migrations.RemoveField(
            model_name='participaciongallos',
            name='resultado',
        ),
        migrations.AddField(
            model_name='participaciongallos',
            name='culminacion1',
            field=models.CharField(blank=True, choices=[('0', 'Muerto'), ('1', 'Tumbado'), ('2', 'Empate'), ('3', 'Anulado')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='participaciongallos',
            name='culminacion2',
            field=models.CharField(blank=True, choices=[('0', 'Muerto'), ('1', 'Tumbado'), ('2', 'Empate'), ('3', 'Anulado')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='participaciongallos',
            name='resultadoidgalpon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
