# Generated by Django 5.1.2 on 2025-04-16 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0030_remove_participaciongallos_culminacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participaciongallos',
            name='resultadoidgalpon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_participaciones', to='streaming.galpon'),
        ),
    ]
