# Generated by Django 5.1.2 on 2025-04-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0031_alter_participaciongallos_resultadoidgalpon'),
    ]

    operations = [
        migrations.AddField(
            model_name='galpon',
            name='pais',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
