# Generated by Django 5.1.2 on 2025-04-17 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0032_galpon_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participaciongallos',
            name='resultadoidgalpon',
        ),
        migrations.AddField(
            model_name='participaciongallos',
            name='idgalpon1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idgalpon1', to='streaming.galpon'),
        ),
        migrations.AddField(
            model_name='participaciongallos',
            name='idgalpon2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idgalpon2', to='streaming.galpon'),
        ),
        migrations.AddField(
            model_name='participaciongallos',
            name='idgalponganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idgalponganador', to='streaming.galpon'),
        ),
        migrations.AddField(
            model_name='participaciongallos',
            name='idgalponperdedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idgalponperdedor', to='streaming.galpon'),
        ),
    ]
