# Generated by Django 5.1.2 on 2025-04-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0033_remove_participaciongallos_resultadoidgalpon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalponGallos',
        ),
    ]
