# Generated by Django 5.1.2 on 2025-04-17 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0034_delete_galpongallos'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallos',
            name='idgalpon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idgalpon_actualmente', to='streaming.galpon'),
        ),
    ]
