# Generated by Django 5.1.2 on 2025-04-17 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0035_gallos_idgalpon'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalponGalloFiesta',
            fields=[
                ('idgalpongallofiesta', models.BigAutoField(primary_key=True, serialize=False)),
                ('eliminado', models.SmallIntegerField(default=0)),
                ('idgallo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='idgallo_galpon_fiesta_inscripcion', to='streaming.gallos')),
                ('idgalponfiesta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='idgalponfiesta_inscripcion', to='streaming.galponfiesta')),
            ],
            options={
                'db_table': 'galpon_gallo_fiesta',
            },
        ),
    ]
