# Generated by Django 5.1.2 on 2025-06-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0036_galpongallofiesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrusel',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='duenio',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='fiesta',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='gallos',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='galpon',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='galponfiesta',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='galpongallofiesta',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='participaciongallos',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='registrofiesta',
            name='eliminado',
        ),
        migrations.RemoveField(
            model_name='streaming',
            name='eliminado',
        ),
    ]
