# Generated by Django 5.1.2 on 2025-06-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0037_remove_carrusel_eliminado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrusel',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comentario',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='duenio',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estado',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fiesta',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gallos',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galpon',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galponfiesta',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='galpongallofiesta',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participaciongallos',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrofiesta',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streaming',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
    ]
