# Generated by Django 5.1.2 on 2025-06-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0038_carrusel_eliminado_comentario_eliminado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='eliminado',
            field=models.SmallIntegerField(default=0),
        ),
    ]
