# Generated by Django 5.1.2 on 2025-06-17 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0039_customuser_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaming',
            name='idevento',
            field=models.OneToOneField(blank=True, db_column='idevento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.evento'),
        ),
    ]
