# Generated by Django 5.1.2 on 2025-06-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0040_alter_streaming_idevento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participaciongallos',
            name='idgalponperdedor',
        ),
        migrations.AlterField(
            model_name='participaciongallos',
            name='culminacion1',
            field=models.CharField(blank=True, choices=[('0', 'Muerto/Tumbado'), ('2', 'Empate'), ('3', 'Anulado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='participaciongallos',
            name='culminacion2',
            field=models.CharField(blank=True, choices=[('0', 'Muerto/Tumbado'), ('2', 'Empate'), ('3', 'Anulado')], max_length=1, null=True),
        ),
    ]
