# Generated by Django 5.1.2 on 2025-06-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0041_remove_participaciongallos_idgalponperdedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ubigeoPais',
            fields=[
                ('eliminado', models.SmallIntegerField(default=0)),
                ('idpais', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ubigeoPais',
            },
        ),
    ]
