# Generated by Django 5.1.2 on 2025-06-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0042_ubigeopais'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubigeopais',
            name='abreviacion',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
