# Generated by Django 5.1.2 on 2025-06-19 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0043_ubigeopais_abreviacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='duenio',
            name='idpais',
            field=models.ForeignKey(blank=True, db_column='idpais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='streaming.ubigeopais'),
        ),
    ]
