# Generated by Django 5.1.2 on 2025-06-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0044_duenio_idpais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duenio',
            name='idpais',
        ),
        migrations.AddField(
            model_name='duenio',
            name='pais',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
